- name: variables to print
  hosts: web
  vars: 
    COURSE: "Devops with Aws"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy M"
  tasks:
   - name: print the information
    snsible.builtin.debug: